version: '3.0'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./mysqli:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web/:/var/www/html/:cached
    environment:
      EASY_READER_DOCKER: "true"
    ports:
      - "80:80"
